/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaveRouteImport } from './routes/_cave'
import { Route as CaveBirthdayRouteImport } from './routes/_cave/birthday'
import { Route as CaveCommandRouteImport } from './routes/_cave/command'
import { Route as CaveIntelRouteImport } from './routes/_cave/intel'
import { Route as CaveSettingsRouteImport } from './routes/_cave/settings'
import { Route as CaveTrainingRouteImport } from './routes/_cave/training'
import { Route as CaveVaultRouteImport } from './routes/_cave/vault'
import { Route as CaveWatchRouteImport } from './routes/_cave/watch'
import { Route as CaveVaultIndexRouteImport } from './routes/_cave/vault/index'
import { Route as CaveVaultIdRouteImport } from './routes/_cave/vault/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaveRoute = CaveRouteImport.update({
  id: '/_cave',
  getParentRoute: () => rootRouteImport,
} as any)
const CaveBirthdayRoute = CaveBirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => CaveRoute,
} as any)
const CaveCommandRoute = CaveCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => CaveRoute,
} as any)
const CaveIntelRoute = CaveIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => CaveRoute,
} as any)
const CaveSettingsRoute = CaveSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CaveRoute,
} as any)
const CaveTrainingRoute = CaveTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => CaveRoute,
} as any)
const CaveVaultRoute = CaveVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => CaveRoute,
} as any)
const CaveWatchRoute = CaveWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => CaveRoute,
} as any)
const CaveVaultIndexRoute = CaveVaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaveVaultRoute,
} as any)
const CaveVaultIdRoute = CaveVaultIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CaveVaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday': typeof CaveBirthdayRoute
  '/command': typeof CaveCommandRoute
  '/intel': typeof CaveIntelRoute
  '/settings': typeof CaveSettingsRoute
  '/training': typeof CaveTrainingRoute
  '/vault': typeof CaveVaultRouteWithChildren
  '/watch': typeof CaveWatchRoute
  '/vault/$id': typeof CaveVaultIdRoute
  '/vault/': typeof CaveVaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday': typeof CaveBirthdayRoute
  '/command': typeof CaveCommandRoute
  '/intel': typeof CaveIntelRoute
  '/settings': typeof CaveSettingsRoute
  '/training': typeof CaveTrainingRoute
  '/watch': typeof CaveWatchRoute
  '/vault/$id': typeof CaveVaultIdRoute
  '/vault': typeof CaveVaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_cave': typeof CaveRouteWithChildren
  '/_cave/birthday': typeof CaveBirthdayRoute
  '/_cave/command': typeof CaveCommandRoute
  '/_cave/intel': typeof CaveIntelRoute
  '/_cave/settings': typeof CaveSettingsRoute
  '/_cave/training': typeof CaveTrainingRoute
  '/_cave/vault': typeof CaveVaultRouteWithChildren
  '/_cave/watch': typeof CaveWatchRoute
  '/_cave/vault/$id': typeof CaveVaultIdRoute
  '/_cave/vault/': typeof CaveVaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthday'
    | '/command'
    | '/intel'
    | '/settings'
    | '/training'
    | '/vault'
    | '/watch'
    | '/vault/$id'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthday'
    | '/command'
    | '/intel'
    | '/settings'
    | '/training'
    | '/watch'
    | '/vault/$id'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/_cave'
    | '/_cave/birthday'
    | '/_cave/command'
    | '/_cave/intel'
    | '/_cave/settings'
    | '/_cave/training'
    | '/_cave/vault'
    | '/_cave/watch'
    | '/_cave/vault/$id'
    | '/_cave/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaveRoute: typeof CaveRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cave': {
      id: '/_cave'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_cave/birthday': {
      id: '/_cave/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof CaveBirthdayRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/command': {
      id: '/_cave/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CaveCommandRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/intel': {
      id: '/_cave/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof CaveIntelRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/settings': {
      id: '/_cave/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof CaveSettingsRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/training': {
      id: '/_cave/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof CaveTrainingRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/vault': {
      id: '/_cave/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof CaveVaultRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/watch': {
      id: '/_cave/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof CaveWatchRouteImport
      parentRoute: typeof CaveRoute
    }
    '/_cave/vault/': {
      id: '/_cave/vault/'
      path: '/'
      fullPath: '/vault/'
      preLoaderRoute: typeof CaveVaultIndexRouteImport
      parentRoute: typeof CaveVaultRoute
    }
    '/_cave/vault/$id': {
      id: '/_cave/vault/$id'
      path: '/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof CaveVaultIdRouteImport
      parentRoute: typeof CaveVaultRoute
    }
  }
}

interface CaveVaultRouteChildren {
  CaveVaultIdRoute: typeof CaveVaultIdRoute
  CaveVaultIndexRoute: typeof CaveVaultIndexRoute
}

const CaveVaultRouteChildren: CaveVaultRouteChildren = {
  CaveVaultIdRoute: CaveVaultIdRoute,
  CaveVaultIndexRoute: CaveVaultIndexRoute,
}

const CaveVaultRouteWithChildren = CaveVaultRoute._addFileChildren(
  CaveVaultRouteChildren,
)

interface CaveRouteChildren {
  CaveBirthdayRoute: typeof CaveBirthdayRoute
  CaveCommandRoute: typeof CaveCommandRoute
  CaveIntelRoute: typeof CaveIntelRoute
  CaveSettingsRoute: typeof CaveSettingsRoute
  CaveTrainingRoute: typeof CaveTrainingRoute
  CaveVaultRoute: typeof CaveVaultRouteWithChildren
  CaveWatchRoute: typeof CaveWatchRoute
}

const CaveRouteChildren: CaveRouteChildren = {
  CaveBirthdayRoute: CaveBirthdayRoute,
  CaveCommandRoute: CaveCommandRoute,
  CaveIntelRoute: CaveIntelRoute,
  CaveSettingsRoute: CaveSettingsRoute,
  CaveTrainingRoute: CaveTrainingRoute,
  CaveVaultRoute: CaveVaultRouteWithChildren,
  CaveWatchRoute: CaveWatchRoute,
}

const CaveRouteWithChildren = CaveRoute._addFileChildren(CaveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaveRoute: CaveRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
